#!/bin/bash
echo "===== BUILDING TOFU COMPILER ====="

echo "[cleaning directory]"
rm -f *.cm*
rm -f .depend

echo "[generating dependendcies]"
ocamldep * > .depend

echo "[beginning compilation]"
echo "[creating lexer]"
ocamllex lexer.mll
echo "[creating parser]"
ocamlyacc parser.mly

ocamlc -c print.mli source.mli keiko.mli tree.mli env.mli parser.mli kgen.mli

echo "[compiling source files]"
ocamlc -c -w -3 print.ml source.ml keiko.ml lexer.ml tree.ml env.ml parser.ml kgen.ml
ocamlc -c tofuc.ml

echo "[building executable]"
ocamlc -o tofuc print.cmo source.cmo keiko.cmo tree.cmo env.cmo lexer.cmo parser.cmo kgen.cmo tofuc.cmo

echo "[finished]"